version: "3"
services:
  hadoop:
    build: .
    image: hadoop-image
    container_name: hadoop-container
    ports:
      - "9870:9870"   # Interface NameNode
      - "9864:9864"   # Interface DataNode
      - "8088:8088"   # Interface ResourceManager
      - "8042:8042"   # Interface NodeManager
      - "22:22"       # Port SSH
    volumes:
      - hadoop_data:/home/iris
      # Montage des scripts MapReduce dans le conteneur
      - ./mapper.py:/opt/hadoop/mapper.py
      - ./reducer.py:/opt/hadoop/reducer.py
    networks:
      - hadoop-net

volumes:
  hadoop_data:

networks:
  hadoop-net:
    driver: bridge
