# version: "3"
services:
  hadoop:
    build: .
    image: hadoop-image
    container_name: hadoop-container
    ports:
      - "9870:9870"   # Interface NameNode
      - "9864:9864"   # Interface DataNode
      - "8088:8088"   # Interface ResourceManager
      - "8042:8042"   # Interface NodeManager
      - "22:22"       # Port SSH
    volumes:
      - hadoop_data:/home/iris
      # Montage des scripts MapReduce dans le conteneur
      - ./mapper.py:/opt/hadoop/mapper.py
      - ./reducer.py:/opt/hadoop/reducer.py

      # 
      - ./scripts:/opt/hadoop/streaming_scripts

      # Monter les fichiers logs depuis leurs emplacements d’origine sur Windows.
      - "C:/laragon/tmp/php_errors.log:/logs_local/php_errors.log:ro"
      - "C:/laragon/bin/apache/httpd-2.4.62-240904-win64-VS17/logs/error.log:/logs_local/error.log:ro"
      - "C:/laragon/bin/apache/httpd-2.4.62-240904-win64-VS17/logs/access.log:/logs_local/access.log:ro"
      - "C:/laragon/data/mysql-8/mysqld.log:/logs_local/mysqld.log:ro"
    networks:
      - hadoop-net
      - tp-elk_elk-network

volumes:
  hadoop_data:

networks:
  hadoop-net:
    driver: bridge
